// AUTO-GENERATED by scripts/gen-registry.mjs. Do not edit by hand.
import type { ComponentType } from "react";
import agentLogCard from "@/components/gallery/agent-log-card/demo";
import campaignPerformance from "@/components/gallery/campaign-performance/demo";
import pricingComparison from "@/components/gallery/pricing-comparison/demo";
import leadFunnelAnalytics from "@/components/gallery/lead-funnel-analytics/demo";
import kpiMetricsDashboard from "@/components/gallery/kpi-metrics-dashboard/demo";
import aiPromptCard from "@/components/gallery/ai-prompt-card/demo";
import clientOverviewCard from "@/components/gallery/client-overview-card/demo";
import taskProgressBoard from "@/components/gallery/task-progress-board/demo";
import adCreativePerformance from "@/components/gallery/ad-creative-performance/demo";
import seoRankingTracker from "@/components/gallery/seo-ranking-tracker/demo";
import conversionRateCard from "@/components/gallery/conversion-rate-card/demo";
import activityTimeline from "@/components/gallery/activity-timeline/demo";
import campaignStatusCard from "@/components/gallery/campaign-status-card/demo";
import leadSourceBreakdown from "@/components/gallery/lead-source-breakdown/demo";
import revenueGrowthChart from "@/components/gallery/revenue-growth-chart/demo";
import appointmentPipeline from "@/components/gallery/appointment-pipeline/demo";
import workflowAutomationCard from "@/components/gallery/workflow-automation-card/demo";
import aiAgentStatusPanel from "@/components/gallery/ai-agent-status-panel/demo";
import notificationCenter from "@/components/gallery/notification-center/demo";
import clientHealthScore from "@/components/gallery/client-health-score/demo";
import adSpendBudgetTracker from "@/components/gallery/ad-spend-budget-tracker/demo";
import formConversionCard from "@/components/gallery/form-conversion-card/demo";
import seoAuditScorecard from "@/components/gallery/seo-audit-scorecard/demo";
import integrationStatusGrid from "@/components/gallery/integration-status-grid/demo";
import teamMemberPerformance from "@/components/gallery/team-member-performance/demo";
import revenueGoalTracker from "@/components/gallery/revenue-goal-tracker/demo";
import webhookEventMonitor from "@/components/gallery/webhook-event-monitor/demo";
import aiUsageAnalytics from "@/components/gallery/ai-usage-analytics/demo";
import customerJourneyMap from "@/components/gallery/customer-journey-map/demo";
import weeklyMarketingReport from "@/components/gallery/weekly-marketing-report/demo";

export type DemoProps = { embed?: boolean };

export const demos: Record<string, ComponentType<DemoProps>> = {
  "agent-log-card": agentLogCard,
  "campaign-performance": campaignPerformance,
  "pricing-comparison": pricingComparison,
  "lead-funnel-analytics": leadFunnelAnalytics,
  "kpi-metrics-dashboard": kpiMetricsDashboard,
  "ai-prompt-card": aiPromptCard,
  "client-overview-card": clientOverviewCard,
  "task-progress-board": taskProgressBoard,
  "ad-creative-performance": adCreativePerformance,
  "seo-ranking-tracker": seoRankingTracker,
  "conversion-rate-card": conversionRateCard,
  "activity-timeline": activityTimeline,
  "campaign-status-card": campaignStatusCard,
  "lead-source-breakdown": leadSourceBreakdown,
  "revenue-growth-chart": revenueGrowthChart,
  "appointment-pipeline": appointmentPipeline,
  "workflow-automation-card": workflowAutomationCard,
  "ai-agent-status-panel": aiAgentStatusPanel,
  "notification-center": notificationCenter,
  "client-health-score": clientHealthScore,
  "ad-spend-budget-tracker": adSpendBudgetTracker,
  "form-conversion-card": formConversionCard,
  "seo-audit-scorecard": seoAuditScorecard,
  "integration-status-grid": integrationStatusGrid,
  "team-member-performance": teamMemberPerformance,
  "revenue-goal-tracker": revenueGoalTracker,
  "webhook-event-monitor": webhookEventMonitor,
  "ai-usage-analytics": aiUsageAnalytics,
  "customer-journey-map": customerJourneyMap,
  "weekly-marketing-report": weeklyMarketingReport,
};
