// AUTO-GENERATED by scripts/gen-registry.mjs. Do not edit by hand.
import type { ComponentMeta } from "./types";
import { meta as agentLogCard } from "@/components/gallery/agent-log-card/meta";
import { meta as campaignPerformance } from "@/components/gallery/campaign-performance/meta";
import { meta as pricingComparison } from "@/components/gallery/pricing-comparison/meta";
import { meta as leadFunnelAnalytics } from "@/components/gallery/lead-funnel-analytics/meta";
import { meta as kpiMetricsDashboard } from "@/components/gallery/kpi-metrics-dashboard/meta";
import { meta as aiPromptCard } from "@/components/gallery/ai-prompt-card/meta";
import { meta as clientOverviewCard } from "@/components/gallery/client-overview-card/meta";
import { meta as taskProgressBoard } from "@/components/gallery/task-progress-board/meta";
import { meta as adCreativePerformance } from "@/components/gallery/ad-creative-performance/meta";
import { meta as seoRankingTracker } from "@/components/gallery/seo-ranking-tracker/meta";
import { meta as conversionRateCard } from "@/components/gallery/conversion-rate-card/meta";
import { meta as activityTimeline } from "@/components/gallery/activity-timeline/meta";
import { meta as campaignStatusCard } from "@/components/gallery/campaign-status-card/meta";
import { meta as leadSourceBreakdown } from "@/components/gallery/lead-source-breakdown/meta";
import { meta as revenueGrowthChart } from "@/components/gallery/revenue-growth-chart/meta";
import { meta as appointmentPipeline } from "@/components/gallery/appointment-pipeline/meta";
import { meta as workflowAutomationCard } from "@/components/gallery/workflow-automation-card/meta";
import { meta as aiAgentStatusPanel } from "@/components/gallery/ai-agent-status-panel/meta";
import { meta as notificationCenter } from "@/components/gallery/notification-center/meta";
import { meta as clientHealthScore } from "@/components/gallery/client-health-score/meta";
import { meta as adSpendBudgetTracker } from "@/components/gallery/ad-spend-budget-tracker/meta";
import { meta as formConversionCard } from "@/components/gallery/form-conversion-card/meta";
import { meta as seoAuditScorecard } from "@/components/gallery/seo-audit-scorecard/meta";
import { meta as integrationStatusGrid } from "@/components/gallery/integration-status-grid/meta";
import { meta as teamMemberPerformance } from "@/components/gallery/team-member-performance/meta";
import { meta as revenueGoalTracker } from "@/components/gallery/revenue-goal-tracker/meta";
import { meta as webhookEventMonitor } from "@/components/gallery/webhook-event-monitor/meta";
import { meta as aiUsageAnalytics } from "@/components/gallery/ai-usage-analytics/meta";
import { meta as customerJourneyMap } from "@/components/gallery/customer-journey-map/meta";
import { meta as weeklyMarketingReport } from "@/components/gallery/weekly-marketing-report/meta";

export const components: ComponentMeta[] = [
  agentLogCard,
  campaignPerformance,
  pricingComparison,
  leadFunnelAnalytics,
  kpiMetricsDashboard,
  aiPromptCard,
  clientOverviewCard,
  taskProgressBoard,
  adCreativePerformance,
  seoRankingTracker,
  conversionRateCard,
  activityTimeline,
  campaignStatusCard,
  leadSourceBreakdown,
  revenueGrowthChart,
  appointmentPipeline,
  workflowAutomationCard,
  aiAgentStatusPanel,
  notificationCenter,
  clientHealthScore,
  adSpendBudgetTracker,
  formConversionCard,
  seoAuditScorecard,
  integrationStatusGrid,
  teamMemberPerformance,
  revenueGoalTracker,
  webhookEventMonitor,
  aiUsageAnalytics,
  customerJourneyMap,
  weeklyMarketingReport,
];

export const getComponent = (slug: string) => components.find((c) => c.slug === slug);
